work in progress

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,4 +1,4 @@
-all: flasher launcher launcher-slot1
+all: flasher launcher launcher-slot1 launcher-mini
 
 clean:
 	rm -f *.bin *.BIN *.map
@@ -25,12 +25,12 @@ flasher: fat32.c flasher.c memory.c sst39sf.c util.c sdcard.c sdcard.asm termina
 	&& mv FLASHER.bin FLASHER.BIN \
 	&& wc -c < FLASHER.BIN
 
-launcher: main.c commands.c fat32.c memory.c terminal.c sdcard.c sdcard.asm ram.asm util.asm rom.asm crc16.asm commands.asm
+launcher: main.c commands.c fat32.c memory.c terminal.c sdcard.c sdcard.asm ram.asm util.asm rom.asm crc16.asm launch_cas.asm
 	zcc \
 	+embedded -clib=sdcc_iy \
 	commands.c fat32.c main.c memory.c terminal.c \
 	util.c sdcard.c sdcard.asm ram.asm util.asm rom.asm \
-	terminal_ext.c crc16.asm commands.asm \
+	terminal_ext.c crc16.asm launch_cas.asm \
 	-startup=0 \
 	-pragma-define:CRT_ORG_CODE=0x7000 \
 	-pragma-define:REGISTER_SP=-1 \
@@ -47,12 +47,12 @@ launcher: main.c commands.c fat32.c memory.c terminal.c sdcard.c sdcard.asm ram.
 	&& wc -c < LAUNCHER.BIN \
 	&& truncate -s 11520 LAUNCHER.BIN
 
-launcher-slot1: main.c commands.c fat32.c memory.c terminal.c sdcard.c sdcard.asm ram.asm util.asm rom.asm crc16.asm commands.asm
+launcher-slot1: main.c commands.c fat32.c memory.c terminal.c sdcard.c sdcard.asm ram.asm util.asm rom.asm crc16.asm launch_cas.asm
 	zcc \
 	+embedded -clib=sdcc_iy \
 	commands.c fat32.c main.c memory.c terminal.c \
 	util.c sdcard.c sdcard.asm ram.asm util.asm rom.asm \
-	terminal_ext.c crc16.asm commands.asm \
+	terminal_ext.c crc16.asm launch_cas.asm \
 	-startup=1 \
 	-pragma-define:CRT_ORG_CODE=0x1000 \
 	-pragma-define:CRT_ORG_DATA=0x6100 \
@@ -68,3 +68,29 @@ launcher-slot1: main.c commands.c fat32.c memory.c terminal.c sdcard.c sdcard.as
 	-create-app -m \
 	&& mv LAUNCHER-SLOT1.bin LAUNCHER-SLOT1.BIN \
 	&& wc -c < LAUNCHER-SLOT1.BIN
+
+mini-launcher: mini-launcher.c fat32-mini.c memory.c sdcard.c sdcard.asm ram.asm rom.asm mini-launcher.asm
+	zcc \
+	+embedded -clib=sdcc_iy \
+	mini-launcher.c fat32-mini.c memory.c sdcard.c \
+	sdcard.asm ram.asm rom.asm mini-launcher.asm \
+	-startup=0 \
+	-pragma-define:CRT_ORG_CODE=0x7000 \
+	-pragma-define:REGISTER_SP=-1 \
+	-pragma-define:CLIB_FOPEN_MAX=0 \
+	-pragma-define:CRT_ON_EXIT=0x10002 \
+	-pragma-define:CRT_ENABLE_EIDI=0x12 \
+	-pragma-define:CLIB_MALLOC_HEAP_SIZE=0 \
+	-pragma-define:CLIB_STDIO_HEAP_SIZE=0 \
+	--max-allocs-per-node3000 \
+	--opt-code-size \
+	-SO3 -bn MINI-LAUNCHER.BIN \
+	-create-app -m \
+	&& mv MINI-LAUNCHER.bin MINI-LAUNCHER.BIN \
+	&& wc -c < MINI-LAUNCHER.BIN \
+	&& truncate -s 11520 MINI-LAUNCHER.BIN
+
+	@if grep -E 'sprintf|printf|fread|fwrite' MINI-LAUNCHER.map ; then \
+		echo "ERROR: stdio symbols found in MINI-LAUNCHER.map!"; \
+		exit 1; \
+	fi
